[workspace]
authors = ["Padraic Shafer <pshafer@bnl.gov>"]
channels = ["conda-forge"]
name = "tiled-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "tiled serve demo"

[dependencies]
python = ">=3.12"
tiled = ">=0.2.8"
